#!/bin/bash
source $BASH_ENV
set -u
INSTANCE_TEMPLATE_QUEUE_SIZE="${INSTANCE_TEMPLATE_QUEUE_SIZE:-30}"
# Create bash array of templates that are to be pushed out of the fifo queue
# Meaning they are the ones to be deleted
readarray -t old_templates < \
  <(gcloud compute instance-templates list \
      --filter name:$INSTANCE_TEMPLATE_SIMPLE_PATTERN \
      --format="value(name)" \
       --sort-by ~CREATION_TIMESTAMP | tail -n +$INSTANCE_TEMPLATE_QUEUE_SIZE)

# Try delete templates in the array
for template_name in "${old_templates[@]}"; do
  if ERR_MSG="$(gcloud compute instance-templates delete -q  $template_name 2>&1)"; then
    echo "INFO: $template_name deleted"
  elif grep "is already being used by" <<< $ERR_MSG; then
    echo "INFO: $template_name is in use and will not be deleted"
  else
    echo "ERROR: $template_name could not be deleted. $ERR_MSG"
  fi
done
