#!/bin/bash
cat > /tmp/tesafetoken <<< "Authorization: Bearer $TE_SAFE_TOKEN"
chmod 600 /tmp/tesafetoken
cat << "EOF" >> $BASH_ENV
get_secret () {
  output="$(curl https://tesafe.timeedit.net/$TE_SAFE_CONTEXT \
                -s --fail-with-body \
                -H @/tmp/tesafetoken -d "$1" )"
	return_code="$?"
	if (($return_code)); then
		echo "$output" >&2
		return $return_code
	fi
    printf "$output"
}
EOF
