#!/bin/bash
cat << "EOF" > /tmp/get_secret
#!/usr/bin/env sh
cat > /tmp/TE_SAFE_TOKEN << EOF2
Authorization: Bearer $TE_SAFE_TOKEN
EOF2
chmod 600 /tmp/TE_SAFE_TOKEN
output="$(curl https://tesafe.timeedit.net/$TE_SAFE_CONTEXT \
        -s --fail-with-body \
        -H @/tmp/TE_SAFE_TOKEN -d "$1" )"
exit_code="$?"
if [ $exit_code -gt 0 ]; then
    echo "$output" >&2
    exit $exit_code
fi
printf "$output"
EOF
chmod 755 /tmp/get_secret
