version: 2.1
orbs:
  utility: timeedit/utility@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/
commands:
  test_generate_get_secret:
    steps:
      - utility/tesafe_get_secrets
      - run:
          name: test get secret
          command: |
            export TE_SAFE_TOKEN=my_dummy
            export TE_SAFE_CONTEXT=dummy
            username="$(/tmp/get_secret /username)"
            if [[ $username == my_username ]]; then
              echo success
            else
              echo Failure
              exit 1
            fi
      - run:
          name: test get secret esc
          command: |
            export TE_SAFE_TOKEN=my_dummy
            export TE_SAFE_CONTEXT=dummy
            username="$(/tmp/get_secret_esc /username)"
            if [[ $username == my_username ]]; then
              echo success
            else
              echo Failure
              exit 1
            fi



jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - test_generate_get_secret
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: timeedit/utility
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
